disabled_rules: # rule identifiers to exclude from running
  - line_length
  - comma
  - colon
  - vertical_whitespace
  - opening_brace
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
